### ISSUE TITLE
Add autoprefixer to build process

### ISSUE THREAD

**Issue by fredericmarx** [Kriesse/wwwtf.berlin#8]
Maybe someone can think of a smart way to do this with our build tools

**Comment by afknapping** [comment]
the build is done with github pages which doesn't let you use custom jekyll plugins.

furthermore autoprefixer is node while the whole gh-pages/jekyll stack is ruby.

some notes what could be done (but would need setup and maintenance and would also make local setup much more complex because of mixing ruby and node enviroments):
- add taskrunner like grunt/gulp or use npm scripts which handle sass compiling and autoprefixing and wrap jekyll serve
- build on travis then check into gh-pages to avoid manual checkin of compiled css
- deploy with surge.sh instead of gh-pages to keep repo clean

(all of this is btw a good chunk of why i have stopped doing development :) happy to share my knowledge if sb interested in digging into it).

tbh the simplest solution imo is to manually keep track of attributes which need vendor prefixes and just write them in :/ maybe there is an online tool that checks production css for missing prefixes via the caniuse api?

**Comment by fredericmarx** [comment]
Yeah, that's what I suspected. As much as I like overengineering things, probably manual is the way to go here

**Comment by sareg0** [comment]
I would love to know more about this at some point (very ignorant to these things at this point), but happy to stay simple for right now
